name: Notify

on:
  workflow_call:

permissions:
  actions: read
  contents: read

jobs:
  slack:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Notify to LINE
        uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: ${{ secrets.LINE_NOTIFY_ACCESS_TOKEN }}
          message: |
            Pull Request CI #${{ github.event.number }} has been completed.
            
            - Lint: ${{ env.DETEKT_RESULT }}
            - Build: ${{ env.BUILD_RESULT }}
            
            ${{ github.event.pull_request.html_url }}
