name: CI

on:
  pull_request_target:
    types: [ opened, reopened, synchronize, ready_for_review, converted_to_draft ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  statuses: write
  checks: write
  actions: read
  contents: read

jobs:
  Lint:
    uses: ./.github/workflows/call-lint.yml

  Build:
    uses: ./.github/workflows/call-build.yml

  Notify:
    if: ${{ !cancelled() }}
    needs:
      [
        Lint,
        Build,
      ]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      DETEKT_RESULT: ${{ needs.Lint.outputs.detekt }}
      BUILD_RESULT: ${{ needs.Build.outputs.build }}
    steps:
      - name: Notify to LINE
        uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: ${{ secrets.LINE_NOTIFY_ACCESS_TOKEN }}
          message: |
            Pull Request CI #${{ github.event.number }} has been completed.

            - Lint: ${{ env.DETEKT_RESULT }}
            - Build: ${{ env.BUILD_RESULT }}

            ${{ github.event.pull_request.html_url }}
